# SPDX-FileCopyrightText: 2021 Andrea Pappacoda
#
# SPDX-License-Identifier: CC0-1.0

name: reuse

on: [push, pull_request]

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fsfe/reuse-action@v3
